[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 300
startCommand = "/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
